#!/bin/sh

export DEFAULT_USER="$USER"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

alias vim="nvim"
alias cz="chezmoi"
alias la="ls -l -a"

alias air='$(go env GOPATH)/bin/air'

#alias claude='NODE_EXTRA_CA_CERTS=~/certs/WEG_Internal_Secure_Certificate_Authority_ROOT.crt claude'

# golang serer autoreload airalias
# alias air='$(go env GOPATH)/bin/air'
